### ISSUE TITLE
if my pet get killed, i can't take a second

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/rpgtest#10]

**Comment by cdqwertz** [comment]
Yep :(
If you rejoin, you will have it again.
PS: I will fix that soon :)

**Comment by cdqwertz** [comment]
fixed.
You cant kill your own pet now :)

**Comment by farfadet46** [comment]
XD thanks ;)

**Comment by farfadet46** [comment]
Sorry but we can't tame a new pet :/

**Comment by cdqwertz** [comment]
I know, but usually the pet should appear when you rejoin

**Comment by cdqwertz** [comment]
(every player can only tame one pet)

**Comment by farfadet46** [comment]
ok if the pet is dead, What we need to do ?

**Comment by cdqwertz** [comment]
Rejoin or delete the file pet in the world folder.
