### ISSUE TITLE
Pet idea: Wolf

### ISSUE THREAD

**Issue by WSDguy2014** [cdqwertz/rpgtest#12]
Wolf can spawn naturally on dirt with grass block, but has untamed wolf. To tame wolf, using bone, maybe zombie or skeleton can drop bones, if killed...

Wolf can help to kill monsters and etc.

To heal tamed wolf, using raw or cooked meat, to heal.
Should be add health bar for wolf...

**Comment by cdqwertz** [comment]
I will add dogs/wolfs :)

**Comment by farfadet46** [comment]
if you want some mobel i can do it for you.

**Comment by cdqwertz** [comment]
@farfadet46 **ok** :)
I am working on some other things yet (character editor, armor, new pet system...

**Comment by farfadet46** [comment]
hum, sorry but i'm not very good on texture XD have you a link to the model ?

**Comment by cdqwertz** [comment]
I thaught you wanted to make the model and I wanted to make the texture...

**Comment by ObaniGemini** [comment]
I think @farfadet46 understood you had made the model and you wanted him to try making textures for it.
Qui pro quo

**Comment by cdqwertz** [comment]
yep maybe....

**Comment by farfadet46** [comment]
XD yep, sorry i'm under medicamentation for big stress :/ after a best read i understand what you whant :) today i'm working on a monster on the base of the cow :) i sent you some picture when i think it's ready

**Comment by farfadet46** [comment]
here a little wolfe for testing 
![loup](https://cloud.githubusercontent.com/assets/11613522/13073402/e3e35916-d49e-11e5-9c94-39889373b3cd.PNG)

**Comment by ObaniGemini** [comment]
I just love the cow-monster. Reminds me a better minotaur !
I really like the wolf, it looks cute :)

**Comment by cdqwertz** [comment]
nice!
It would be neat if you could make them a bit more blocky...

**Comment by cdqwertz** [comment]
I am working on the monster api, that I can add your mobs easily!

**Comment by ObaniGemini** [comment]
Are you gonna rewrite everything from scratch ? ;)

**Comment by cdqwertz** [comment]
I am just working on the monster api not on the pets api

**Comment by farfadet46** [comment]
ok i need some motivation XD
i have a little problem with the bones for the animation i always forget how it's works XD
WIP ! ;)

**Comment by farfadet46** [comment]
![wolf2](https://cloud.githubusercontent.com/assets/11613522/13091267/99418566-d4fa-11e5-8921-84924365fd77.PNG)
![wolf3](https://cloud.githubusercontent.com/assets/11613522/13091268/9d63ebe8-d4fa-11e5-9162-2f1910d3a939.PNG)
![wolf4](https://cloud.githubusercontent.com/assets/11613522/13091269/9d8ddb9c-d4fa-11e5-8e48-5bd63bde3c1f.PNG)

new one !

**Comment by cdqwertz** [comment]
**that looks nice!**

**Comment by WSDguy2014** [comment]
Looks good...

**Comment by cdqwertz** [comment]
@farfadet46 could you send me your model? - so I can add it and make  a texture for it. 
Which license has your model?

**Comment by farfadet46** [comment]
do you want the animated model ?
the license is CC0 ;)

**Comment by cdqwertz** [comment]
yep, could you send me the .blend file?

**Comment by farfadet46** [comment]
ok maybe you can make a new UV MAP XD

![capture](https://cloud.githubusercontent.com/assets/11613522/13196559/96bf8098-d7d1-11e5-8b55-8dfc18dc5836.PNG)
it's a 7zip: https://up1.ca/#QbXLya0jxOST8Cz1K8LZdA

**Comment by ObaniGemini** [comment]
I don't know if the nose is needed, it would probably make the model heavier for something that could be handled by the texture.
Anyway, great work !

**Comment by cdqwertz** [comment]
I am going to add this model soon :)
But I need to add animations to the pets api first.

**Comment by cdqwertz** [comment]
I am working on a texture for your model : 
![tex](https://cloud.githubusercontent.com/assets/12814327/13357404/4c444228-dcaa-11e5-9648-efb23bc14090.png)

**Comment by farfadet46** [comment]
;) star-wolf
nice.

**Comment by cdqwertz** [comment]
I added your model to the game!

**Comment by WSDguy2014** [comment]
alright very good, keep going, if you completed for adding pets 100% I will close issue.

**Comment by cdqwertz** [comment]
pets will be never completed.
But if you want, you can open a new issue "ideas for pets".

**Comment by WSDguy2014** [comment]
cdqwertz, now you working on progress for wolf texutre?

**Comment by cdqwertz** [comment]
no, I think its finished. I posted a pic on the forum :)
