### ISSUE TITLE
Backup files present in repository

### ISSUE THREAD

**Issue by ExcaliburZero** [cdqwertz/rpgtest#14]
Currently there are several files in the project's repository that are backup files. The backup files are the ones that end with `~`.

These files generaly shouldn't be placed in repositories as they are not needed.

Thus it would be a good to remove the backup files and create a `.gitignore` file within the main directory of the repository to prevent further backup files from being commited into the repository.

**Comment by cdqwertz** [comment]
I already said somewhere, that I will remove them if I have time, bc I am very busy at the moment.

**Comment by ObaniGemini** [comment]
And doesn't take much time to create a .gitignore. Just add one line with `*~` and another with `~*`

**Comment by ExcaliburZero** [comment]
All of the backup files throughout the repo can be removed by running the following command in the main directory of the repository:

```
find . -name '*~' -delete
```

**Comment by ExcaliburZero** [comment]
I have created a pull request which fixes this issue at #15 .
