### ISSUE TITLE
we can get 2 cobblestone with crafting 9 stones ?

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/rpgtest#17]
see in craft.ini
can you explain why ?
nice work anyway :D

**Comment by cdqwertz** [comment]
I think If you would get only one, it would be too difficult to build bigger things out of cobble...

**Comment by farfadet46** [comment]
when you dig a stone you get a cobble or a stone ?

just an idea : maybe an hammer to make coble ?

**Comment by cdqwertz** [comment]
if you dig stone you get a craft item named stone, it cant be placed

**Comment by farfadet46** [comment]
oh ok i don't see that XD
