### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/rpgtest#2]
i have no sound in your subgame :(

**Comment by cdqwertz** [comment]
I will add sound soon (maybe tomorrow).
This subgame is still WIP :)

**Comment by farfadet46** [comment]
yes i understand :)

nice work anyway :)

**Comment by cdqwertz** [comment]
Thank you

**Comment by cdqwertz** [comment]
Sorry, I didnt have much time today, I was working on the class system/api :)
But I will add sound soon :)
