### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [cdqwertz/rpgtest#20]
Currently it seems to lack one. I suggest AGPLv3+ :)

**Comment by cdqwertz** [comment]
lgpl-2.1 is a free license, isnt it?
The most modules for this game are licensed under the lgpl-2.1 license. (some exceptions)
Take a look at the license files of the mods :)

**Comment by pizzamaker** [comment]
Correct! I suggest a license for the overall project, though, just to make it clear :)

**Comment by cdqwertz** [comment]
The problem is, that some mods have their own license.... But I think I will add a README.txt to make that a bit more clear :)
