### ISSUE TITLE
Ask 4aiman, to help translate Russian language on your subgame.

### ISSUE THREAD

**Issue by WSDguy2014** [cdqwertz/rpgtest#30]
Ask 4aiman, to help translate Russian language on your subgame "RPGtest". Because some many Russian peoples, can't know English language. Need to add Russian language.

P.S. - I can't register on Minetest Forums, to ask a private message for you. Because i got IP banned for spamming, I'm NOT spammer. I hate new feature is: CONFIRMATION OF REGISTRATION (Sorry for caps lock).
For example: Watch out, roses have _ _ _ _ _s!:
This question is a means of preventing automated form submissions by spambots.

**Comment by cdqwertz** [comment]
Hmm, I think I will ask someone :)

PS : I would ask a mod on irc about the forum acc.

**Comment by farfadet46** [comment]
ok but 4aiman is not a good boy :(  #minetestforfun as some issue with him :/

**Comment by 4aiman** [comment]
Heh :)

4aiman is an ok boy for as long as one won't set up a server of his game only to later say it is *4aiman* who should maintain that server's issues with a modified versions of his game.
He was overwhelmed by the amount of nonsense from #minetestforfun.

Other than that he's okay.
He should use stronger passwords, though :p

**Comment by farfadet46** [comment]
:D
