### ISSUE TITLE
"Story" bookmark underground

### ISSUE THREAD

**Issue by azekillDIABLO** [cdqwertz/rpgtest#32]
**When i span (idk if this word exist) i saw a bookmark named story far of ~200 block and i realised it was underground** 
![screenshot_20160630_173911](https://cloud.githubusercontent.com/assets/17685062/16494642/52d5fc92-3eea-11e6-8eff-f670e97d9917.png)
![screenshot_20160630_173827](https://cloud.githubusercontent.com/assets/17685062/16494649/5a869bfe-3eea-11e6-9a22-3322f0176b67.png)

**Comment by cdqwertz** [comment]
You are right. The story waypoint is really buggy - I will fix that soon :)
