### ISSUE TITLE
Class specific items

### ISSUE THREAD

**Issue by cdqwertz** [cdqwertz/rpgtest#4]
Do you have any ideas for **class specific** items? - Post them here!
Class specific items are items which can only be used by a specific class (e.g. spear - warrior)
You can post your ideas for **classes** here too :

**Comment by farfadet46** [comment]
OK do you have some classes aldready known ?

Farmer
warior
'red' magician => the color mean a specific attribute like red = lava, blue = water ...
crafter - builder (maybe two different class ? )
...

**Comment by cdqwertz** [comment]
I think crafter and builder arnt real classes.
Everyone can craft and build :)

**Comment by farfadet46** [comment]
yep but he can ... yeah you'r right XD

**Comment by ObaniGemini** [comment]
- Seller (can sell)
- Settler (can own some areas)
- Soldier (has better weapons)
- Magician (has some powers like healing, fast movements,...)
- Thief (can as some ways to steal in chests, open locked doors,...)


All those classes would have specific items and capacities, of course :)
And also those are just ideas, I don't think "Settler" would fit as an only class for example ^^.

**Comment by farfadet46** [comment]
why not make some specialisation 
like in falout, the player can add some point on specialisations
just see that on gameplay on Youtube. it's just an idea :)

**Comment by cdqwertz** [comment]
Thief is a great idea :D
