### ISSUE TITLE
Crashing at Startup with latest stable Minetest

### ISSUE THREAD

**Issue by twirlimp** [cdqwertz/rpgtest#42]
I get this error as soon as I load the world.

```
minetest: /build/minetest-XWO5LM/minetest-0.4.14/src/util/serialize.h:278: void writeF1000(irr::u8*, irr::f32): Assertion `i >= F1000_MIN && i <= F1000_MAX' failed.
Aborted
```

There are no mods installed, and I tried this with fresh worlds with worlgen v5, v6, and v7 so that's not it.

This happens soon after the language-selection-formspec comes up, and I don't have to click on it for the error to happen, although sometimes I can play for a few seconds into the game before it crashes.

**Comment by twirlimp** [comment]
Earlier on the terminal there's this warning, however it turned out to be irrelevant after fixing it.


```
alkotob/.minetest/games/rpgtest/mods/skills/init.lua:72
WARNING[Main]: Undeclared global variable "i" accessed at /home/alkotob/.minetest/games/rpgtest/mods/skills/init.lua:73

```

**Comment by rubenwardy** [comment]
This is not caused by rpgtest, but by Minetest. To fix, don't use a debug build. Weird how this is on a fresh build

**Comment by twirlimp** [comment]
What's weird is that this debug build is from the main public repo on my distro

**Comment by cdqwertz** [comment]
Does minetest game work?
