### ISSUE TITLE
Fishing rod is pretty OP (and other items)

### ISSUE THREAD

**Issue by WSDguy2014** [cdqwertz/rpgtest#43]
I was going to fishing that have a long range and its possible to interact blocks (not tested on entities) from far away while selecting at fishing rod on hotbar. Also i spam left-clicked on water source with fishing rod to catch a fish by a chance, fishing rod is never runs out durability.
It's pretty much a free food.

Same thing with chisel, it has unlimited durability.

Also its possible to pick up item drops (for some reason are melee weapon) and interact a blocks thing by right-clicking (for example, a box. Not tested on entities) far away while selecting at bow (does not require arrows, shots infinitely) on hotbar.

**Comment by cdqwertz** [comment]
https://github.com/cdqwertz/rpgtest/commit/d0b54f3beb3b96435dc1e793cd7e9c89df40c02a
