### ISSUE TITLE
Monsters spawns only on water for some reason?

### ISSUE THREAD

**Issue by WSDguy2014** [cdqwertz/rpgtest#47]
Why you did do that? Can you fix monster spawning?

I also monsters does not spawn on cave?

I saw monsters does spawn on air at +y height, only must be spawned angry clouds.

**Comment by cdqwertz** [comment]
Ok, I see I need to rework the spawning code.

**Comment by cdqwertz** [comment]
https://github.com/cdqwertz/rpgtest/commit/ea36aca3475548a8b5fdc52f7434b0cf8cd96cb9
