### ISSUE TITLE
Activating Grow ability on air = crashes.

### ISSUE THREAD

**Issue by WSDguy2014** [cdqwertz/rpgtest#48]
Also, it does not allow to grow wheat quickly, cactus, sugarcane (papyrus) and carrot.

Even crashes while pointing on entity, to activate grow ability.

@cdqwertz, don't forget to add a update post on Minetest forum at RPGtest subgame.

**Comment by cdqwertz** [comment]
Ok, I guess I will have to fix that xD.

**Comment by cdqwertz** [comment]
> Also, it does not allow to grow wheat quickly, cactus, sugarcane (papyrus) and carrot.
Might add

**Comment by cdqwertz** [comment]
https://github.com/cdqwertz/rpgtest/commit/6afafc0ec544f90f87809c8d46612bc3dcbd89b1
