### ISSUE TITLE
trunck is too small

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/rpgtest#5]
It's a nice idea to make the trunck a little small node but if we place a torch on it, there is a problem, the torch don't touch the node and it's like floating in the air :D

**Comment by cdqwertz** [comment]
yea, but I think, there is an easy way to Fix that :)
( Just make the torch longer (drawtype mesh) )

**Comment by farfadet46** [comment]
yep good idea too :) if you want i can try to make a 3d mesh for it :)

**Comment by cdqwertz** [comment]
I added an 3d model with some nice particles (torch mod)
