### ISSUE TITLE
need info about potion

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/rpgtest#6]
When i eat a potion, i have no idea how long i can use it after eat it :/

EDIT: maybe some particles ?

**Comment by cdqwertz** [comment]
Yea, I will add information about this.
10 secs

**Comment by cdqwertz** [comment]
Added :D
If you drink a potion, you will see something like [effect] + <effect>!
After 10 secs it will tell you something like [effect] - <effect>
Healing potions work different they just say [hp] + 10
