### ISSUE TITLE
Potion's timer is too short

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/rpgtest#8]
The duration of the effect is too short
another problem, for the jump i think change the gravity is a little problem because i can change direction in air :D

**Comment by cdqwertz** [comment]
1. I think 10 seconds are enought
2. I like that :)

**Comment by cdqwertz** [comment]
Maybe, I could add something like a lvl 2 potion :)

**Comment by farfadet46** [comment]
yep ;)
