### ISSUE TITLE
Ideas for kits

### ISSUE THREAD

**Issue by cdqwertz** [cdqwertz/rpgtest#9]
Post your ideas for **kits** here!
There are some kits:

- basic
- hard
- customer
- peasan

**Comment by farfadet46** [comment]
kit ? like medikit ?

**Comment by cdqwertz** [comment]
you can choose a kit using /kit <name>
A kit is a basic equipment for players - take a look at the forum topic.
I will add a wiki page for kits soon :)

**Comment by farfadet46** [comment]
add a system to give the list of all kit avalaible if no "name" added after the "/kit"
like
if <param> == nil
bla bla bla
end
 :)

**Comment by farfadet46** [comment]
the kit peasan =
10 seed
1 hoe
1 bucket

**Comment by cdqwertz** [comment]
nice idea, I will add this kit soon :)

**Comment by farfadet46** [comment]
can you edit your first post to add the kit aldready in the game please ?

**Comment by farfadet46** [comment]
A kit builder ? 

to make a small house like :
20 bricks
20 wood planks
20 wool ? (i know there is no wool ingame yet :p )

**Comment by cdqwertz** [comment]
@farfadet46 : nice idea :) (There is wool...)

**Comment by farfadet46** [comment]
ok for the wool :) and ok too for the easy gaming if the player can get all the resources for build the first house
